FROM node:12

WORKDIR /app

ADD package.json /app/package.json
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate

COPY . .

RUN npm run build

FROM node:12

COPY . .

EXPOSE 3001

CMD ["npm", "start"]