version: '3'
services:
  message-board-api:
    container_name: mb-api
    build:
      context: ./mb-backend/
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres
    container_name: "postgres"
    env_file:
      - .env
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  # message-board-frontend:
  #   build:
  #     context: ./mb-frontend/
  #     dockerfile: Dockerfile.dev
  #   image: message-board-frontend:latest
  #   environment:
  #     PORT: 3000
  #     PROXY_API: http://playground-web-backend:8080/
  #   ports:
  #     - 3000:3000